[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/league"
  to = "/.netlify/functions/get-league"
  status = 200

[[redirects]]
  from = "/api/submit"
  to = "/.netlify/functions/submit-transactions"
  status = 200

[[redirects]]
  from = "/api/ping"
  to = "/.netlify/functions/ping"
  status = 200

[[redirects]]
  from = "/api/blobtest"
  to = "/.netlify/functions/blobtest"
  status = 200

[[redirects]]
  from = "/api/cleanup"
  to = "/.netlify/functions/cleanup-dupes"
  status = 200

[[redirects]]
  from = "/api/audit"
  to = "/.netlify/functions/audit"
  status = 200

[[redirects]]
  from = "/api/fix"
  to = "/.netlify/functions/fix-known-issues"
  status = 200
